.gitattributes

Files and directories with the attribute export-ignore won’t be added to archive files. This will prevent composer from downloading unnecessary files (i.e: tests) when --prefer-dist is set.

Create .gitattributes with basic export-ignores

---

lib/PhpParser/Autoloader.php
lib/bootstrap.php

This is probably a really edge case but I think it's worth considering at least.
I'm working on a project that uses PHP-Parser to analyze code. This project can be executed via an executable PHP file or a Phar file. In both cases, a composer autoloader is registered and PHP-Parser's autoloader kicks in.
Then, to analyze the code of the project the user wants, the composer autoloader of the current working directory is also registered. This means there are two composer autoloaders working at the same time - which is usually OK, except the PHP-Parser autoloader always requires the Autoloader class file, causing a "cannot redeclare class" error.
Other than defining a constant (`define('PHP_PARSER_AUTOLOADER_LOADED', true)`), the only way to avoid loading the class file more than once is by …

Ensure compatibility with multiple composer autoloaders

---

lib/PhpParser/NodeTraverser.php
test/PhpParser/NodeTraverserTest.php

Fixes #184
I added a flag to the constructor of `NodeTraverser` to disable the default behavior of cloning all nodes when traversing the AST.

Added a flag to NodeTraverser to avoid cloning nodes

---

lib/PhpParser/Autoloader.php

Minor change to avoid relying on dirname(__DIR__) == PhpParser
This is useful for downstream distribution where we'd like to provides both v1.x and v2.x installed in a different tree

make autoloader more PSR-4

---

composer.json

Technically PHPUnit 4 doesn't support PHP 7.

Use phpunit 5 if we can rather than 4

---

.travis.yml

Runs the tests on the newer Trusty containers since this repo is not affected by the mysql issues in the trusty container. 
Added benefit, This provides the current HHVM version (3.18.1 as of this PR) and will track with each release (i.e. will be 3.19 when 3.19 is released). ... **you are currently on an EOL versions of HHVM since precise was dropped back at hhvm 3.6**
If testing against HHVM LST versions is desired follow this guide. https://docs.travis-ci.com/user/languages/php#HHVM-versions
NOTE: If testing against HHVM in php 7 mode is desired: HHVM php 7 mode currently has an issue that messes up composer under php 7 mode, see facebook/hhvm#7198 once that BUG is fixed HHVM PHP 7 mode testing could be added

Run on Trusty Beta Container

---

doc/3_Other_node_tree_representations.markdown

Unless I am mistaken the NodeDumper is _not_ needed when outputting to JSOn, so the following line  can be removed from the docs:
```php
$nodeDumper = new PhpParser\NodeDumper;
```

Removes unneeded code from JSON encoding example.

---

doc/5_FAQ.markdown

FAQ's code examples use incorrect method, so this update fixes it

Use the correct method from NodeVisitor interface

---

doc/2_Usage_of_basic_components.markdown

Example code in [Example: Converting namespaced code to pseudo namespaces](https://github.com/nikic/PHP-Parser/blob/master/doc/2_Usage_of_basic_components.markdown#example-converting-namespaced-code-to-pseudo-namespaces) does not convert namespaces to pseudo namespaces,
since `PhpParser\Node\Name::toString()` does not accept namespace separator from this commit: a910f6a247b9041401558a0a4335773103848c89
In this pull request, to convert namespaces, I replaced pseudo namespace generation code.

Fix example code to work

---

doc/4_Code_generation.markdown

Generated example was incorrect - you cannot define import alias:
use Some\Other\Thingy as SomeClass;
and then define a class with the same name:
abstract class SomeClass ...
Class names changed to avoid conflict between import alias and abstract class name.

Fixed incorrect class inheritance in code generation example (docs)

---

grammar/php5.y
grammar/php7.y

There's a missing semicolon in the grammar files for php7 and php5. Not really critical but would be nice to have it fixed.

Fix missing semicolon in yacc grammar files

---

CHANGELOG.md
UPGRADE-3.0.md
UPGRADE-4.0.md
grammar/README.md

Hi
I am busy helping fix spelling in the documentation of popular PHP projects.
Here are some minor fixes

Fix spelling in documentation

---

test/PhpParser/ErrorTest.php
test/PhpParser/LexerTest.php
test/PhpParser/NodeAbstractTest.php
test/PhpParser/NodeFinderTest.php

I've refactored some tests, using:
- `assertCount` instead of `count` function;
- `assertTrue` instead of strict comparison with `true` keyword;
- `assertFalse` instead of strict comparison with `false` keyword;
- `assertNull` instead of strict comparison with `null` keyword;
- `assertObjectHasAttribute` and `assertObjectNotHasAttribute` instead of `isset` function.

Refactoring tests

---

lib/PhpParser/NodeAbstract.php

This ensures this piece of code is still working after changing the namespace of the class like done with [PHP-Scoper](https://github.com/humbug/php-scoper)

Replace string by class call

---

phpunit.xml.dist

A little improvement for `phpunit.xml.dist`: remove flags that have the default value [as upstream](https://phpunit.de/manual/6.5/en/appendixes.configuration.html) and colorize the output with `colors=true` :)

Remove flags from phpunit.xml that have default value and colorize

---

lib/PhpParser/NodeTraverser.php

At the moment, when `NodeTraverser` is extended and constructor used for dependency injection, there is hidden and unneded dependency on `parent__construct()` call:
```php
use PhpParser\NodeTraverser;
final class NodeTypeResolverNodeTraverser extends NodeTraverser
{
public function __construct(MetadataNodeVisitor $metadataNodeVisitor)
{
// this would crash, since property is `null`
foreach ($this->visitors ...) {
}
// ...
}
}
```
Using `[]` as default value would prevent similar bugs.

Remove NodeTraverser dependency on parent::__construct()

---

lib/PhpParser/Node/Expr/StaticCall.php

At least I don't *think* it can (the constructor definitely tries to prevent it being a string).

StaticCall::$name cannot be a string

---

doc/2_Usage_of_basic_components.markdown
doc/component/Walking_the_AST.markdown

This PR adds missed documentation for already merged https://github.com/nikic/PHP-Parser/pull/536

Document new `DONT_TRAVERSER_CURRENT_AND_CHILDREN` constant

---

bin/php-parse

This is a patch for #605, I have no knowledge of the internals of this library so I touched only `bin/php-parse`; it should be enough.

Print messages to stderr in bin/php-parse and fix exit status

---

lib/PhpParser/NodeVisitor/NameResolver.php
test/PhpParser/NodeVisitor/NameResolverTest.php

The NameResolver is currently not working with the re newly introduced ArrowFunction node of PHP 7.4 in the 4.2.2 release. This line of code fixes the issue.

Resolve return type of arrow functions

---

lib/PhpParser/Node/Scalar/String_.php
lib/PhpParser/PrettyPrinter/Standard.php

This change is made to avoid notices caused by
https://wiki.php.net/rfc/base_convert_improvements
(seen with `php -d error_reporting=E_ALL vendor/bin/phpunit`)

Avoid notices in php 7.4 with hexdec/base_convert

---

.gitignore
lib/PhpParser/Node/Stmt/ClassLike.php
lib/PhpParser/Node/Stmt/Class_.php
lib/PhpParser/Node/Stmt/Interface_.php
lib/PhpParser/Node/Stmt/Trait_.php
test/PhpParser/Builder/TraitTest.php
test/PhpParser/Node/Stmt/ClassTest.php
test/PhpParser/Node/Stmt/InterfaceTest.php

As there is `getMethods()` at `ClassLike`, I often tend to use `getProperties()` and `getConstants()`, but there are none. I understood that's probably because only `getMethods()` is in `ClassLike` for all 3 sub-classes.
Yet the API is inconsistent and confusing. This would fix that.
```php
foreach ($class->stmts as $stmt) {
if (! $stmt instanceof Property) {
continue;
}
// do something
}   
```
vs.
```php
foreach ($class->getMethods() as $method) {
// do something
}   
```
This keeps happening to me last 2 years so I finally do something about it

add getProperties() to Class_/Trait_ and getConstants() to Class_/Interface_

---

lib/PhpParser/Node/Stmt/ClassLike.php
test/PhpParser/Node/Stmt/ClassTest.php

This makes it easier to get a property by name from a ClassLike.

Add `getProperty` to `ClassLike`

---

LICENSE

The license text should exactly match the official BSD-3-clause license, otherwise the license has been misused, and GitHub can't detect the license. It says this repo has a custom license, but Packagist thinks it is BSD-3-clause due to the composer.json.

Corrected license text

---

grammar/rebuildParsers.php

phpyacc is a sh file and should not be run via the php interpreter, but directly.

Fixed rebuildParsers.php

---

lib/PhpParser/Node/Expr/Array_.php

When used to destructure items are optional just as with `list()`. E.g. `[$a, , $b] = [1, 2, 3];`.

Update Array_ annotations, items are nullable

---

test/code/formatPreservation/listRemoval.test

A regression after fixing https://github.com/nikic/PHP-Parser/pull/699. The empty line in the try block is removed.

FPPP failing tests

---

lib/PhpParser/PrettyPrinter/Standard.php

I noticed some methods in the Standard PrettyPrinter is **private**, can they be upgraded to **protected** to ease when extending it?

Upgrade some PrettyPrinter methods to protected

---

README.md

Fixes #733 by updating docs to indicate that parsing PHP 8.0 is supported (as indicated by changes in recent 4.x releases: https://github.com/nikic/PHP-Parser/releases). Note: unsure if PHP 8.0 is "fully" supported yet, so this may be pre-emptive, I didn't check if "everything" works yet.

Updated README to indicate that parsing PHP 8.0 code is supported

---

lib/PhpParser/Lexer.php

Remove useless code left from old implementation

---

lib/PhpParser/Internal/TokenStream.php
test/code/formatPreservation/rewriteVariableInterpolationString.test

Php parses `{` as an array `[0 => 386,1 => '{',2 => 12,]` so this check doesn't work properly. My edit fixes this.

Fixed type vs string

---

.gitattributes

Adds `.github` directory to `.gitattributes` file with an `export-ignore` rule.
This also aligns all `export-ignore` rules for more readability.
Thank you.

Add .github directory to .gitattributes export-ignore

---

lib/PhpParser/Builder/Namespace_.php

Hi, just a little detail. This should fix invalid return type of docs
Other builders already return specific type.

make Namespace_ builder return Namespace_

---

grammar/phpyLang.php
grammar/rebuildParsers.php

This change moves the functions that are used to process the "phpy pseudo grammar language" into their own script.
The aim is to make the phpy grammar transformation accessible to consumers of the package, by allowing the functions script to be loaded without also loading the execution of the `rebuildParsers.php` script.

Move phpy functions to separate file

---

lib/PhpParser/ParserAbstract.php

Otherwise, it's somewhat incompatible with the phpdoc definition:
> In the case where a DocComment spans multiple lines, every line MUST start with an asterisk (*)
that SHOULD be aligned with the first asterisk of the opening clause.
Source: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md

ParserAbstract: add missing '*' to the phpdoc

---

lib/PhpParser/Builder/ClassConst.php
lib/PhpParser/Builder/Class_.php
lib/PhpParser/Builder/Function_.php
lib/PhpParser/Builder/Interface_.php
lib/PhpParser/Builder/Method.php
lib/PhpParser/Builder/Param.php
lib/PhpParser/Builder/Property.php
lib/PhpParser/Builder/Trait_.php
lib/PhpParser/BuilderHelpers.php
test/PhpParser/Builder/ClassConstTest.php
test/PhpParser/Builder/ClassTest.php
test/PhpParser/Builder/FunctionTest.php
test/PhpParser/Builder/InterfaceTest.php
test/PhpParser/Builder/MethodTest.php
test/PhpParser/Builder/ParamTest.php
test/PhpParser/Builder/PropertyTest.php
test/PhpParser/Builder/TraitTest.php
test/PhpParser/BuilderHelpersTest.php

Adds `addAttribute()` method to Builders of all nodes supporting attributes with `BuilderHelpers::normalizeAttribute()` usage inside so we can pass both `Node\Attribute` and `Node\AttributeGroup` instances

Add addAttribute() method to Builders with normalizer

---

lib/PhpParser/BuilderHelpers.php
test/PhpParser/BuilderHelpersTest.php

In this PR I've added missing tests for methods of `BuilderHelpers` and change all `elseif` to normal `if` statements to reduce cognitive load.

Add missing tests for methods of BuilderHelpers

---

README.md
bin/php-parse
doc/2_Usage_of_basic_components.markdown
doc/README.md
doc/component/Performance.markdown

This PR makes @derickr happy by using the word Xdebug instead of XDebug :)

chore: use the word Xdebug instead of XDebug

---

lib/PhpParser/BuilderHelpers.php

In order to get rid of the flag in `BuilderHelpers::normalizeNameCommon()` I have moved all the logic related to the normalization of the name to the `BuilderHelpers::normalizeName()` method and expr-related stuff to the `BuilderHelpers::normalizeNameOrExpr()` method which later calls the basic `normalizeName()` as well

Simplify BuilderHelpers::normalizeName() implementation

---

lib/PhpParser/PrettyPrinterAbstract.php
test/code/formatPreservation/arrayInsertionWithComments.test

This fixes #804 by printing the `$insertStr` before the comments, in the case of items added to multiline arrays.

Print comma before comments for new array item (fixes #804)

---

README.md

Support for PHP 8.1 was added on November 20th in 50953a2. This pull request, when merged, reflects this support in the project's README file.

Reflect support for PHP 8.1 in the README

---

lib/PhpParser/Node/Scalar/LNumber.php
test/PhpParser/Node/Scalar/NumberTest.php
test/PhpParser/NodeAbstractTest.php

Allows to use `$number->rawValue` to work with numberic seaprator https://github.com/nikic/PHP-Parser/pull/615
Now we have to work with actual tokens on the position to get the original value.
When accepted, I will add the same feature for `DNumber`.
Replaces https://github.com/nikic/PHP-Parser/pull/655

[LNumber] Add rawValue attribute to LNumber to allow numeric separator etc.

---

grammar/php5.y
grammar/php7.y
lib/PhpParser/Node/Scalar/DNumber.php
lib/PhpParser/Parser/Php5.php
lib/PhpParser/Parser/Php7.php
test/PhpParser/Node/Scalar/DNumberTest.php
test/PhpParser/NodeAbstractTest.php

Mirror to https://github.com/nikic/PHP-Parser/pull/832

[DNumber] Add rawValue attribute to hold the original value

---

grammar/php5.y
grammar/php7.y
grammar/phpyLang.php
lib/PhpParser/Node/Scalar/String_.php
lib/PhpParser/Parser/Php5.php
lib/PhpParser/Parser/Php7.php
test/PhpParser/Node/Scalar/StringTest.php
test/PhpParser/NodeAbstractTest.php

In Rector we have to hack around tokens to get the original value, because the `parse()` method flattens original information:
https://github.com/nikic/PHP-Parser/blob/a6e34665fd6a2bcefc924cb5fd73788767ae510e/lib/PhpParser/Node/Scalar/String_.php#L55-L72
We could use also attribute value, but it would require more grammar changes.
Closes https://github.com/nikic/PHP-Parser/pull/577
Also fixes https://github.com/nikic/PHP-Parser/issues/576

[String_] Add rawValue attribute

---

lib/PhpParser/PrettyPrinter/Standard.php

Cast (boolean) and (integer) should be written as (bool) and (int), (double) and (real) as (float), (binary) as (string).

Short scalar cast

---

lib/PhpParser/ParserAbstract.php

Class `PhpParser\Parser\Tokens` not exists in current version

ParserAbstract: remove undefined class in `use`

---

lib/PhpParser/NodeFinder.php

At the moment, the node finder does always returns generic `Node` or `Node[]` result:
```php
$nodeFinder = new NodeFinder();
// what is it? only Node[]
$returns = $nodeFinder->typeAwareNodeFinder->findInstanceOf($node, Return_::class);
```
In fact, we know it must be instances of `Return_`. To teach IDE/static analyzer this know-how, we have to add it manually in every result:
```php
/** @var Return_[] $resturn */
$returns = $nodeFinder->typeAwareNodeFinder->findInstanceOf($node, Return_::class);
```
This PR suggest to do the same already on `php-parser` level:

[docs] Add generic types to NodeFinder to allow returning exact type in static analysis

---

doc/component/Pretty_printing.markdown

The `$lexer` variable no longer exist in the example.

Fix pretty printing example

---

.github/workflows/main.yml
lib/PhpParser/Builder/ClassConst.php
lib/PhpParser/Builder/Class_.php
lib/PhpParser/Builder/EnumCase.php
lib/PhpParser/Builder/Enum_.php
lib/PhpParser/Builder/Function_.php
lib/PhpParser/Builder/Interface_.php
lib/PhpParser/Builder/Method.php
lib/PhpParser/Builder/Param.php
lib/PhpParser/Builder/Property.php
lib/PhpParser/Builder/Trait_.php
lib/PhpParser/BuilderFactory.php
lib/PhpParser/Lexer.php
lib/PhpParser/Lexer/Emulative.php
lib/PhpParser/Node/Attribute.php
lib/PhpParser/Node/MatchArm.php
lib/PhpParser/Node/Param.php
lib/PhpParser/Node/Stmt/ClassConst.php
lib/PhpParser/Node/Stmt/EnumCase.php
lib/PhpParser/NodeTraverser.php
phpstan-baseline.neon

closes https://github.com/nikic/PHP-Parser/issues/905

declare list types

---

lib/PhpParser/Builder/Param.php
test/PhpParser/Builder/ParamTest.php

By making flags on the Param builder configurable we can influence which are past to the Param node representation.

[4.x] Add constructor property promotion

---

lib/PhpParser/Builder/Param.php
test/PhpParser/Builder/ParamTest.php

By making flags on the Param builder configurable we can influence which are past to the Param node representation.

[5.x] Add constructor property promotion

---

.github/workflows/main.yml

Updates the GitHub Actions from V2 (Deprecated) to V3 (using Node16 instead of Node12)
This will resolve the warning show at https://github.com/nikic/PHP-Parser/actions/runs/5106129693
-  https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Update main.yml to use GitHub Actions V3

---

lib/PhpParser/Node/Expr/CallLike.php

If I understand correctly, `VariadicPlaceholder` will only exists on first arg, after it, it will always an Arg. so no need whole loop to verify another `VariadicPlaceholder`, this can speed up usage on `getArgs()` method as assert check.

Early return false after VariadicPlaceholder check on CallLike::isFirstClassCallable()

---

lib/PhpParser/Node/Expr/ArrowFunction.php
lib/PhpParser/Node/Expr/Match_.php
lib/PhpParser/Node/Param.php

After upgrading to v5.0.0, there were some missing type annotations in the AST nodes class which those types were correctly annotated in v4.x
Add the missing types
I am working on a project that generates TypeScript type definition files for the PHP Parser dumped AST nodes(by `-j` option of the  CLI command). those types should be generated automatically through the PHP source code, it depends on the type annotation to infer the proper TS types. 
It works very well for v4. today, I tried to migrate it to v5. and when I rerun the `generate` script. I found the missing types.

Fix missing type annotations in AST nodes

---

lib/PhpParser/NodeFinder.php

No need to create `FindingVisitor` and `NodeTraverser` next when passed `$nodes` is empty array.

Improve performance of find() and findFirst() when passed $nodes is empty array

---

.gitattributes

build: Exclude grammar from export git artifact

---

.gitattributes

If you need indentation to align `export-ignore` in the same position, please let me know.

Add dev tool files to export-ignore

---

lib/PhpParser/Comment.php
lib/PhpParser/Error.php
lib/PhpParser/Node.php
lib/PhpParser/NodeAbstract.php

when working with line numbers, one could easily do off-by-one errors because of assumptions about whether line numbers start at `0` or `1`.
the added phpdocs make sure that static analysis, no matter whether phpstan or psalm, can detect errors like that. psalm will also work with these `phpstan`-prefixed phpdocs.

Prevent off-by-one errors in line-number related methods

---

lib/PhpParser/Internal/PrintableNewAnonClassNode.php

Fixes https://github.com/nikic/PHP-Parser/issues/986

Fix deprecated Optional parameter before required parameter on PrintableNewAnonClassNode

---

.github/workflows/main.yml
lib/PhpParser/Node.php
lib/PhpParser/Node/Identifier.php
lib/PhpParser/Node/Name.php
test/PhpParser/Node/IdentifierTest.php

goal: ease working in projects which are static analysis covered.
we are doing the same thing in PHPStan with https://github.com/phpstan/phpstan-src/pull/3013#pullrequestreview-1998289070

Declare more precise phpdoc types

---

CHANGELOG.md

Fix a tiny typo
`Dereferenceing` to `Dereferencing`
it is also for being consistent with other parts of the codebase: https://github.com/search?q=repo%3Anikic%2FPHP-Parser%20dereferencing&type=code

Fix a typo: `Dereferenceing` to `Dereferencing`

---

doc/component/JSON_representation.markdown

I was converting the structure into Go, and saw that a very minor issue exists with the JSON example.

Fix the invalid JSON structure

---

lib/PhpParser/Builder/ClassConst.php
lib/PhpParser/BuilderFactory.php
lib/PhpParser/BuilderHelpers.php
test/PhpParser/BuilderHelpersTest.php
test/fixtures/Suit.php

Normalize enum value to ClassConstFetch

---

lib/PhpParser/Node/Identifier.php
lib/PhpParser/Node/Name.php

psalm knows the `lowercase-string` type for a few years already and [PHPStan learned it](https://github.com/phpstan/phpstan-src/pull/3438) a few weeks ago.
//cc @VincentLanglet

More precise `toLowerString()` return type

---

tools/fuzzing/target.php

Updates fuzzer target.php to new version of PHP-Parser. The method getTokens() has been removed.
The PHPStan issue is not related to the PR.

update target.php to new PHP-Parser version

---

lib/PhpParser/Node/Stmt/ClassLike.php
lib/PhpParser/NodeVisitor/FindingVisitor.php

searched the codebase with `(?<!getSubNodeNam)es\(\):` and added `list`-types where appropriate

Use more precise list-types for getter methods

---

Makefile
doc/component/FAQ.markdown
lib/PhpParser/NodeVisitor/NodeConnectingVisitor.php
lib/PhpParser/NodeVisitor/ParentConnectingVisitor.php
test/PhpParser/NodeVisitor/NodeConnectingVisitorTest.php
test/PhpParser/NodeVisitor/ParentConnectingVisitorTest.php

closes https://github.com/nikic/PHP-Parser/issues/1055
we observed perf improvements on a similar visitor in https://github.com/staabm/phpstan-dba/issues/667#issuecomment-2565559874

Support WeakReferences in NodeConnectingVisitor

---

UPGRADE-5.0.md

Documentation says `creatForHostVersion()` but obviously means `createForHostVersion()`.

Minor spelling `creatForHostVersion()` -> `createForHostVersion()`

---

lib/PhpParser/Node/Expr/CallLike.php
test/PhpParser/Node/Expr/CallableLikeTest.php

Hello!
This method returns the named argument that matches the given `$name`, or the positional (unnamed) argument that exists at the given `$position`, otherwise, returns `null` for first-class callables or if no match is found.
I found myself duplicating this logic over and over again, so thought it would be a good idea to just PR it.
For a given CallLike, I often need to target a particular *parameter*. Take for example this function signature:
```php
function test(int $foo = 24, int $bar = 42);
```
and let's say that I need to do something with `$bar` (which has name `bar` and is at position `1`) if it's provided in the call. Now I can simply use:
```php
$arg = $node->getArg('bar', 1);
```
which would return the following:
```php
test(); // null
test(...); // null
test(24, 42); // …
```

feat: add CallLike::getArg() method

---

composer.json

A similar fix is needed on master

Drop branch-alias on 4.x

---

lib/PhpParser/Node/Expr/ArrayItem.php
lib/PhpParser/Node/Expr/ClosureUse.php
lib/PhpParser/Node/Scalar/DNumber.php
lib/PhpParser/Node/Scalar/Encapsed.php
lib/PhpParser/Node/Scalar/EncapsedStringPart.php
lib/PhpParser/Node/Scalar/LNumber.php
lib/PhpParser/Node/Stmt/DeclareDeclare.php
lib/PhpParser/Node/Stmt/PropertyProperty.php
lib/PhpParser/Node/Stmt/StaticVar.php
lib/PhpParser/Node/Stmt/UseUse.php

@TomasVotruba per our discussion at https://github.com/rectorphp/rector-phpunit/pull/513#issuecomment-3200861058

Use @deprecated above class to allow static analyzer like PHPStan detect deprecation
