lib/PhpParser/NodeDumper.php

analog to https://github.com/nikic/PHP-Parser/commit/b7ffdbbb929f9f07780a236659d1d1baf68ef137

prevent a unnecessary concat

---

lib/PhpParser/Node/Expr/AssignOp.php
lib/PhpParser/Node/Expr/AssignRef.php

I don't think these need to be there anymore.

Remove some unecessary @property doc comments

---

lib/PhpParser/Builder/FunctionLike.php
lib/PhpParser/Builder/Method.php
lib/PhpParser/Builder/Param.php
lib/PhpParser/BuilderAbstract.php
lib/PhpParser/Node/Expr/Closure.php
lib/PhpParser/Node/FunctionLike.php
lib/PhpParser/Node/Param.php
lib/PhpParser/Node/Stmt/ClassMethod.php
lib/PhpParser/Node/Stmt/Function_.php

Allows this & similar bugs to be caught: https://github.com/vimeo/psalm/commit/983c6fd6c4e5fbc1b8f18bb496f2a5183ef44614

Add NullableType to types of properties/args that offer it

---

doc/component/Lexer.markdown

To make it more natural and readable

Docs: highlight interface + PHP 7 return types

---

.travis.yml

Prevents possible error when adding a second line

travis: add dash to make command format united

---

lib/PhpParser/Node/Stmt/ClassMethod.php

See this comment for details: https://github.com/Roave/BetterReflection/issues/378#issuecomment-341089928

ClassMethod stmts property can be null

---

lib/PhpParser/Autoloader.php
lib/PhpParser/NodeTraverserInterface.php

Add methods visibility

---

composer.json

`PHPUnit 7` has just released, fully optimize for `PHP 7`, with return and scalar types :+1:

Support PHPUnit 7

---

UPGRADE-4.0.md

Fix typo in UPGRADE-4.0

---

lib/PhpParser/BuilderFactory.php
lib/PhpParser/Error.php

Some missing docs and redundant casts :)

Fixes from PHPStan

---

lib/PhpParser/NodeTraverser.php
test/PhpParser/NodeTraverserTest.php

Detailed explanation in https://github.com/nikic/PHP-Parser/issues/534
I'm not sure about naming, so any advice is highly appreciated.
Fixes https://github.com/nikic/PHP-Parser/issues/534

Add new constant to be returned from enterNode() to not travers current and child nodes

---

lib/PhpParser/Node/Stmt/ClassLike.php
test/PhpParser/Node/Stmt/ClassTest.php

Follow up to #630
Last method missing from all possible clas like stmts

add getTraitUses() method to ClassLike

---

.gitattributes

Add .gitattributes to .gitattributes

---

CHANGELOG.md
lib/PhpParser/BuilderHelpers.php
lib/PhpParser/ParserAbstract.php
test/PhpParser/Builder/ParamTest.php
test/code/parser/stmt/function/builtinTypeDeclarations.test

I tried to follow the same steps when the `object` type was added, but I'm not sure whether anything else is needed or not. :)

Add support for the mixed type

---

lib/PhpParser/Node/Const_.php

I think I'm right about this one :)

Fixed PHPDoc typo

---

lib/PhpParser/Builder/Use_.php

Same as https://github.com/nikic/PHP-Parser/pull/747
I've noticed one more problem in PHPStorm

Update Use_ builder to return specific type

---

doc/component/Error_handling.markdown

Missing argument in the getMessageWithColumnInfo call

missing argument

---

CHANGELOG.md

Update CHANGELOG.md (minor last release year fix)

---

lib/PhpParser/BuilderFactory.php
test/PhpParser/BuilderFactoryTest.php

In this PR I've added two builders for named arguments and attributes which later could be  used for Class/Properties builders

Add Attribute builder and support for named args

---

lib/PhpParser/Node/Arg.php
lib/PhpParser/Node/IntersectionType.php
lib/PhpParser/ParserAbstract.php

Unused use statements must be removed.

No unused imports

---

lib/PhpParser/ConstExprEvaluator.php
lib/PhpParser/Lexer.php
lib/PhpParser/Lexer/Emulative.php
lib/PhpParser/NameContext.php
lib/PhpParser/Node/Arg.php
lib/PhpParser/Node/Expr/ArrayDimFetch.php
lib/PhpParser/Node/Expr/ArrayItem.php
lib/PhpParser/Node/Expr/Exit_.php
lib/PhpParser/Node/Expr/Yield_.php
lib/PhpParser/Node/Name.php
lib/PhpParser/Node/Param.php
lib/PhpParser/Node/Stmt/Break_.php
lib/PhpParser/Node/Stmt/Catch_.php
lib/PhpParser/Node/Stmt/Continue_.php
lib/PhpParser/Node/Stmt/Declare_.php
lib/PhpParser/Node/Stmt/EnumCase.php
lib/PhpParser/Node/Stmt/Namespace_.php
lib/PhpParser/Node/Stmt/PropertyProperty.php
lib/PhpParser/Node/Stmt/Return_.php
lib/PhpParser/Node/Stmt/StaticVar.php
lib/PhpParser/Node/Stmt/TryCatch.php
lib/PhpParser/NodeDumper.php
lib/PhpParser/NodeVisitor/NameResolver.php
lib/PhpParser/Parser.php
lib/PhpParser/ParserAbstract.php
lib/PhpParser/ParserFactory.php

Adds ? before type declarations for parameters with a default null value

Nullable type declaration for default null value

---

lib/PhpParser/Comment.php
lib/PhpParser/Node/Name.php
lib/PhpParser/Node/Scalar/String_.php
lib/PhpParser/ParserAbstract.php
lib/PhpParser/PrettyPrinter/Standard.php

Replaces superfluous elseif with if.

No superfluous elseif

---

composer.json

ext-json: `JsonSerializable`
ext-ctype: `ctype_*()`

Add JSON extension to required in composer.json

---

lib/PhpParser/Node/Param.php
test/PhpParser/Node/ParamTest.php

Can I have this please? I think I [need](https://github.com/jaem3l/unfuck/pull/4) it ...

Add isReadonly on Param node

---

lib/PhpParser/NodeVisitor/NameResolver.php

The type of argument `type` is always `int` so I added it.

added type int to argument of addAlias function

---

lib/PhpParser/Builder/Use_.php
lib/PhpParser/NameContext.php
lib/PhpParser/Node/Stmt/GroupUse.php
lib/PhpParser/Node/Stmt/Use_.php
lib/PhpParser/Node/UseItem.php
lib/PhpParser/NodeVisitor/NameResolver.php

for better static analysis support in consuming projects

Use more precise Use_::TYPE_* types

---

lib/PhpParser/Node/PropertyItem.php
lib/PhpParser/Node/UseItem.php

Closes https://github.com/nikic/PHP-Parser/issues/969

Fix parent class of PropertyItem and UseItem

---

.github/workflows/main.yml

Updates `actions/checkout` to version 4.

Update actions/checkout to v4

---

grammar/php.y

To solve the issue: https://github.com/nikic/PHP-Parser/issues/1005

Fix a typo: Dereferencable to Dereferenceable

---

lib/PhpParser/Node/Param.php
test/PhpParser/Node/ParamTest.php

Closes https://github.com/nikic/PHP-Parser/issues/1048

Promoted properties with hooks do not need visibility modifier

---

lib/PhpParser/NodeTraverser.php

early check the error condition to ease reading the common case in the loop
at best [reviewed with whitespaces ignored](https://github.com/nikic/PHP-Parser/pull/1056/files?w=1)

Simplify NodeTraverser->traverseArray()
